on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        with:
          node-version: '20.x'
          
      - name: Linting Action
        uses: ryanclark/lint-action@v1.15.0
        with:
          node-version: '20.x'
          
      - name: Install Dependencies
        run: npm install

      - name: Analyzing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
